# Generated by Django 5.0 on 2024-03-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateTaskModel',
            new_name='TaskModel',
        ),
    ]
